services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    restart: unless-stopped

  web_kafka:
    build: ./backend
    ports:
      - "8002:8000"
    depends_on:
      - kafka
      - mongo_kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_URI=mongodb://mongo_kafka:27017
      - MONGO_DB_NAME=distributed_database_kafka
    restart: unless-stopped

  mongo_kafka:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_kafka_data:/data/db
    restart: unless-stopped

  nginx_kafka:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/lua:/etc/nginx/lua
    depends_on:
      - web_kafka
    restart: unless-stopped

volumes:
  mongo_kafka_data:
